### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by mifozski** [DarrenTsung/DTAnimatorStateMachine#1]
Would be nice to have some example. Like how to to set it up and use. I have no clue what should I pass as a `TStateMachine` to the definition of `DTStateMachineBehaviour`.

**Comment by siordache94** [comment]
bumpin just in case

**Comment by DarrenTsung** [comment]
Oh thanks, forgot about this, I can put up an example repo somewhere this weekend!

**Comment by oxvr-tec** [comment]
Bumping again.

**Comment by jayderyu** [comment]
It's been 1 year. Is there an example.

I managed to get the states in the animator. however, the extension for configuring them I am still unsure of.

So how about a simple example please :)

**Comment by DarrenTsung** [comment]
Hi, thanks for the bump, I realize that I forgot to create an example repo. 

I'm currently not working with Unity or plan on supporting this repository, but I do have an abandoned WIP game which uses DTAnimatorStateMachine as the state machine for the game state and also simple AI which I just made public.
https://github.com/DarrenTsung/laserbeak

Here's an example of deriving and using the state machine behavior: 
https://github.com/DarrenTsung/laserbeak/blob/master/Assets/Game/States/MainMenuState/MainMenuState.cs

**Comment by jayderyu** [comment]
WOW. Thanks, and super thanks for the incredibly quick response. I appreciate this.

Well since you have moved on. I wish good fortune to what you're working on and with.

**Comment by jayderyu** [comment]
For anyone else who ends up here.  A reference to a state machine, for example, can be found in the file here.
https://github.com/DarrenTsung/laserbeak/blob/master/Assets/Game/GameStateMachine.cs
